name: Gemini PR Review
env:
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  gemini-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get PR Diff
        id: get-diff
        run: |
          DIFF=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          # Escape backslashes, double quotes, dollar signs, and add \n at end of each line.
          DIFF_ESCAPED=$(echo "$DIFF" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\$/\\\$/g; s/$/\\n/' | tr -d '\n')
          echo "diff=$DIFF_ESCAPED" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          python -m pip install google-generativeai

      - name: Run Gemini Review Script
        id: gemini-review
        env:
          GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}'
        run: |
          # Write the diff into a file that our script will read.
          echo "${{ steps.get-diff.outputs.diff }}" > diff.txt
          # Run the external Python script.
          python gemini_review.py

      - name: Post Gemini Review
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('review.md', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '## 🤖 Gemini Code Review\n\n' + review
            });
